title = "ESDStudioProject"
[project_info]
name = "Ascension-ER"
base_directory = "C:\\Users\\benja\\Modding\\Elden Ring\\Projects\\Ascension\\ESD\\Ascension"
game_directory = "F:\\SteamLibrary\\steamapps\\common\\ELDEN RING\\Game"
mod_directory = "C:\\Users\\benja\\Modding\\Elden Ring\\Projects\\Ascension"
game = "er"
