title = "ESDDescriptions"
[maps.m00_00_00_00]
4000 = "Mysterious Shinobi"
4010 = "Master Jarwright"
4040 = "Apprentice Frasca"
1300 = "Jar of Rebirth"
4030 = "Emissary of Mohgwyn"
1200 = "Jar of Promise"
1400 = "Statue of Draconic Communion"
1500 = "Altar of Advancement"
1600 = "Duelist Atticus - Caelid"
1700 = "Duelist Atticus - Limgrave"
1800 = "Bard Sangeet"
4020 = "Duelist Lysander"
4050 = "Jar of Cultivation"
4060 = "Stitchmaster Gerald"
