title = "ESDStudioProject"
[project_info]
name = "Cinders-ER"
base_directory = "C:\\Users\\benja\\Modding\\Elden Ring\\Projects\\Cinders-ER\\# ESD\\Cinders-ER"
game_directory = "F:\\SteamLibrary\\steamapps\\common\\ELDEN RING\\Game"
mod_directory = "C:\\Users\\benja\\Modding\\Elden Ring\\Projects\\Cinders-ER"
game = "er"
